name: Daily Feature Extraction

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at 00:00 UTC
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  run-feature-extraction:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run feature extraction script
        run: python full_feature_extraction.py
