name: Stage 2 Lexical Feature Extraction

on:
  schedule:
    - cron: "20 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual run from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run Lexical Feature Extraction on latest PhiUSIIL and Mendeley files
        run: |
          mkdir -p lexical_features

          get_latest_file() {
            pattern="$1"
            latest=$(ls -t http_status/*"$pattern"*.csv 2>/dev/null | head -n 1)
            if [ -f "$latest" ]; then
              echo "$latest"
            fi
          }

          latest_phiusiil=$(get_latest_file "PhiUSIIL")
          latest_mendeley=$(get_latest_file "Mendeley")

          if [ -n "$latest_phiusiil" ]; then
            echo "Processing latest PhiUSIIL file: $latest_phiusiil"
            python lexical_feature_extractor.py --input-file "$latest_phiusiil" --output-dir lexical_features
          else
            echo "No PhiUSIIL CSV file found."
          fi

          if [ -n "$latest_mendeley" ]; then
            echo "Processing latest Mendeley file: $latest_mendeley"
            python lexical_feature_extractor.py --input-file "$latest_mendeley" --output-dir lexical_features
          else
            echo "No Mendeley CSV file found."
          fi

      - name: Upload Lexical Features
        uses: actions/upload-artifact@v4
        with:
          name: lexical_features
          path: lexical_features/
          if-no-files-found: warn

      - name: Commit and push Lexical feature files
        run: |
          git config user.name "Ifeoluwa Oseni"
          git config user.email "ifeoseni@gmail.com"

          echo "Pulling latest changes from origin main..."
          git pull origin main --rebase || git pull origin main

          if [ -d "lexical_features/" ] && [ "$(ls -A lexical_features/)" ]; then
            echo "Adding lexical_features/ files to git..."
            git add lexical_features/
            if ! git diff --cached --quiet; then
              echo "Committing lexical feature updates..."
              git commit -m "Auto-update: Lexical feature extraction - $(date '+%Y-%m-%d %H:%M:%S')"
              echo "Pushing changes to origin main..."
              git push origin main || {
                echo "Push failed, pulling and retrying..."
                git pull origin main --rebase
                git push origin main
              }
            else
              echo "No changes to commit for lexical features"
            fi
          else
            echo "No lexical feature files to commit"
          fi
