name: Lexical Feature Extraction Workflow

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: "20 0 * * *" # Runs daily at 00:20 UTC

jobs:
  run-lexical-extraction:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dataset: [phiusiil, mendeley]
        include:
          - dataset: phiusiil
            input_pattern: "*PhiUSIIL*.csv"
          - dataset: mendeley
            input_pattern: "*Mendeley*.csv"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MTECH }} # Your PAT for pushing back to the repo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas tldextract

      - name: Setup paths and find latest file
        id: setup
        run: |
          INPUT_DIR="http_status"
          OUTPUT_DIR="lexical_features"
          SCRIPT="lexical_feature_extractor.py"
          INPUT_PATTERN="${{ matrix.input_pattern }}"

          mkdir -p "$INPUT_DIR"
          mkdir -p "$OUTPUT_DIR"

          # Find the most recent file matching the pattern
          LATEST_INPUT_FILE=$(find "$INPUT_DIR" -maxdepth 1 -name "$INPUT_PATTERN" -type f -printf '%T@ %p\n' | sort -n | tail -n 1 | cut -d' ' -f2-)

          if [ -z "$LATEST_INPUT_FILE" ]; then
            echo "::error::No file found in $INPUT_DIR matching $INPUT_PATTERN"
            exit 1
          fi

          BASENAME=$(basename "$LATEST_INPUT_FILE")
          # Use prefix lexical_features_ as output prefix (matching script output)
          OUTPUT_FILE_PATH="$OUTPUT_DIR/lexical_features_${BASENAME}"

          echo "LATEST_INPUT_FILE=$LATEST_INPUT_FILE" >> $GITHUB_OUTPUT
          echo "OUTPUT_FILE_PATH=$OUTPUT_FILE_PATH" >> $GITHUB_OUTPUT
          echo "SCRIPT=$SCRIPT" >> $GITHUB_OUTPUT

      - name: Run Lexical Feature Extraction for ${{ matrix.dataset }}
        run: |
          echo "Running: ${{ steps.setup.outputs.SCRIPT }}"
          python "${{ steps.setup.outputs.SCRIPT }}" \
            --input-file "${{ steps.setup.outputs.LATEST_INPUT_FILE }}" \
            --output-dir "$(dirname "${{ steps.setup.outputs.OUTPUT_FILE_PATH }}")"

      - name: Upload Lexical Features
        uses: actions/upload-artifact@v4
        with:
          name: lexical_features_${{ matrix.dataset }}_${{ github.run_id }}
          path: ${{ steps.setup.outputs.OUTPUT_FILE_PATH }}
          if-no-files-found: error

      - name: Commit and Push Lexical Feature Files
        env:
          TOKEN: ${{ secrets.MTECH }}
        run: |
          git config user.name "Ifeoluwa Oseni"
          git config user.email "ifeoseni@gmail.com"
          git pull origin main --rebase

          git add lexical_features/
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update: Lexical features for ${{ matrix.dataset }}"
            git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "No changes to commit for ${{ matrix.dataset }}"
