name: Stage 2 Lexical Feature Extraction

on:
  schedule:
    - cron: "20 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Also allows manual run from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Lexical Feature Extraction
        run: |
          mkdir -p lexical_features
          for input_csv in http_status/*.csv; do
            if [ -f "$input_csv" ]; then
              echo "Processing $input_csv with lexical_feature_extractor.py"
              python lexical_feature_extractor.py --input-file "$input_csv" --output-dir lexical_features
            else
              echo "Warning: No CSV files found in http_status/ to process."
            fi
          done

      - name: Upload Lexical Features
        uses: actions/upload-artifact@v4
        with:
          name: lexical_features
          path: lexical_features/
          if-no-files-found: warn

      - name: Commit and push Lexical feature files
        run: |
          git config user.name "Ifeoluwa Oseni"
          git config user.email "ifeoseni@gmail.com"

          echo "Cleaning untracked files in lexical_features/ directory..."
          git clean -fdx lexical_features/

          echo "Pulling latest changes from origin main..."
          git pull origin main --rebase || git pull origin main

          if [ -d "lexical_features/" ] && [ "$(ls -A lexical_features/)" ]; then
            echo "Adding lexical_features/ files to git..."
            git add lexical_features/
            if ! git diff --cached --quiet; then
              echo "Committing lexical feature updates..."
              git commit -m "Auto-update: Lexical feature extraction - $(date '+%Y-%m-%d %H:%M:%S')"
              echo "Pushing changes to origin main..."
              git push origin main || {
                echo "Push failed, pulling and retrying..."
                git pull origin main --rebase
                git push origin main
              }
            else
              echo "No changes to commit for lexical features"
            fi
          else
            echo "No lexical feature files to commit"
          fi
