name: Two Features With Test Dataset

on:
  schedule:
    - cron: "30 22 * * *" # 22:30 UTC = 23:30 Lagos (WAT)
  workflow_dispatch:

jobs:
  run-http-checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        input_file:
          - cleaned_data/PhiUSIIL_cleaned_v2.csv
          - cleaned_data/Mendeley_cleaned_v2.csv

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create HTTP Status Output Directory
        run: mkdir -p http_status

      - name: Run HTTP Status Checker for ${{ matrix.input_file }}
        id: run_checker
        run: |
          INPUT_BASENAME=$(basename "${{ matrix.input_file }}")
          echo "Running HTTP status check for ${{ matrix.input_file }}"
          OUTPUT_FILE=$(python two_http_status_checker.py --input-file "${{ matrix.input_file }}" --output-dir http_status)
          echo "output_file=${OUTPUT_FILE}" >> $GITHUB_OUTPUT

      - name: Upload HTTP Status Features for ${{ matrix.input_file }}
        uses: actions/upload-artifact@v4
        with:
          name: http_status_features
          path: ${{ steps.run_checker.outputs.output_file }}
          if-no-files-found: error

  run-lexical-analysis:
    runs-on: ubuntu-latest
    needs: run-http-checks

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Lexical Feature Extraction
        run: |
          python lexical_feature_extractor.py

      - name: Upload Lexical Features
        uses: actions/upload-artifact@v4
        with:
          name: lexical_features
          path: lexical_features/
          if-no-files-found: warn
